### PR TITLE
Refactored eventhtml and acrticle html to fix delete button bug

### LINKED ISSUE #57: Articles: delete
Given a user wants to remove a previously stored news article
When the user performs a gesture on the delete affordance
Then the article should be deleted

### PR DESCRIPTION
**Pull request by dmccracken13**
# Description
Refactored eventshtml and articlehtml to exclude delete function for friend components
Fixes #57 #30 
Allowing user to delete friend's articles and events

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
# Testing Instructions
git fetch --all
git checkout dm-StretchCSS
code .
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/scripts/articles/articleHTML.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 //J.Kaset HTML representation of one article. 
 
 export const Article = (articleObj) => {
+  if(articleObj.userId === parseInt(sessionStorage.getItem("activeUser"))) {
```
Comment (Heath-Lester) [inline src/scripts/articles/articleHTML.js:5]: "activeUser does not need to be parsed into an integer because the id it is being compared to in the API is a string instead of a number."

**Review by Heath-Lester — CHANGES_REQUESTED** [review]

**Review by Heath-Lester — APPROVED** [review]
